elasticsearch:
  image: elasticsearch
  command: --network.bind_host "0.0.0.0" --network.publish_host "_non_loopback:ipv4_"
  ports:
    - '9200'

logstash:
  image: logstash
  command: logstash -e 'input { syslog { type => "syslog" port => 5140 codec => "json" } } filter { if [type] == "syslog" { json { source => "message" } } } output { elasticsearch { hosts => ["elasticsearch:9200"] } stdout {  } }'
  ports:
    - '5140:5140/udp'
  links:
    - 'elasticsearch:elasticsearch'

kibana:
  image: kibana
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  ports:
    - '5601:5601'
  links:
    - 'elasticsearch:elasticsearch'
